"""init

Revision ID: fba62bc773b9
Revises: 
Create Date: 2026-05-29 19:51:53.582158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fba62bc773b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('articles', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('articles', 'file_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('articles', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('articles', 'cover_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=512),
               nullable=True)
    op.alter_column('articles', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('articles', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('articles', 'published_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.create_index(op.f('ix_articles_file_path'), 'articles', ['file_path'], unique=True)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_unique_constraint(None, 'articles', ['slug'])
    op.alter_column('categories', 'category_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.alter_column('file_categories', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('file_categories', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_file_categories_id'), 'file_categories', ['id'], unique=False)
    op.drop_constraint(op.f('CATEGORY_FK'), 'file_categories', type_='foreignkey')
    op.drop_constraint(op.f('FILE_FK'), 'file_categories', type_='foreignkey')
    op.create_foreign_key(None, 'file_categories', 'files', ['file_id'], ['id'])
    op.create_foreign_key(None, 'file_categories', 'categories', ['category_id'], ['id'])
    op.alter_column('files', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('files', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=True)
    op.create_index(op.f('ix_files_file_path'), 'files', ['file_path'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.alter_column('project_tags', 'tag',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('project_tags', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_project_tags_id'), 'project_tags', ['id'], unique=False)
    op.drop_constraint(op.f('FK_PROJECT'), 'project_tags', type_='foreignkey')
    op.create_foreign_key(None, 'project_tags', 'projects', ['project_id'], ['id'])
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('projects', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projects', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.create_foreign_key(op.f('FK_PROJECT'), 'project_tags', 'projects', ['project_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_project_tags_id'), table_name='project_tags')
    op.alter_column('project_tags', 'project_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('project_tags', 'tag',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_path'), table_name='files')
    op.alter_column('files', 'file_name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('files', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.drop_constraint(None, 'file_categories', type_='foreignkey')
    op.drop_constraint(None, 'file_categories', type_='foreignkey')
    op.create_foreign_key(op.f('FILE_FK'), 'file_categories', 'files', ['file_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('CATEGORY_FK'), 'file_categories', 'categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_index(op.f('ix_file_categories_id'), table_name='file_categories')
    op.alter_column('file_categories', 'file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('file_categories', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'parent_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('categories', 'category_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_file_path'), table_name='articles')
    op.alter_column('articles', 'published_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('articles', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('articles', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('articles', 'cover_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=512),
               nullable=False)
    op.alter_column('articles', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('articles', 'file_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('articles', 'slug',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
