server {
    listen 80;
    server_name stefanspitse.nl www.stefanspitse.nl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name stefanspitse.nl www.stefanspitse.nl;

    ssl_certificate /etc/letsencrypt/live/stefanspitse.nl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stefanspitse.nl/privkey.pem;

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api {
        proxy_pass http://backend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
